# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kadai09_LoginAuthentication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kadai09_LoginAuthentication

   pod 'Firebase/Core'
   pod 'Firebase/Auth'
　　
　　use_frameworks!
　　pod 'ChameleonFramework/Swift'

end
